### PR TITLE
Allows space separated argument to be passed when double quoted.

### PR DESCRIPTION
**Pull request by capaximperii**
Example:
  File delete <name>
can accept:
  File delete "Filename that contains spaces"

### CODE REVIEW

**Comment by SeeSpotRun** [comment]
FIlenames with spaces appear to be handled just fine already:
```
move.py:
--------
#!/usr/bin/env python3
"""move.
Usage:
  move <from> <to>
"""

from docopt import docopt

if __name__ == '__main__':
    arguments = docopt(__doc__)
    print(arguments)
```

Yields:
```
$ ./move.py "A filename with spaces.doc" "New name.doc"
{'<from>': 'A filename with spaces.doc',
 '<to>': 'New name.doc'}
```

**Comment by TylerTemp** [comment]
This is actually handled by commandline and do not need to handle in code:

```bash
$ cat quote.py 
import sys
print(sys.argv)

$ python quote.py "A filename with spaces.doc" "New name.doc"
['quote.py', 'A filename with spaces.doc', 'New name.doc']
```

as you can see, the most-outside quote in commandline does not passed to program.

**Comment by capaximperii** [comment]
That is correct @TylerTemp , The application where I ran into the problem was a CLI tool which had to do it all by itself without relying on the command shell or bash to do it, since the command could be initiated via web or a remote connection.
The question is whether a docopt application should always make that assumption of being launched via a command shell that is capable of such parsing.

**Comment by SeeSpotRun** [comment]
@capaximperii: I think for that case you should use a separate procedures to parse the command line into the argv format, then pass that to docopt.
I think `shlex.split()` will do what you want (https://docs.python.org/3/library/shlex.html)

**Comment by capaximperii** [comment]
@SeeSpotRun Indeed shlex can achieve it but I would not use it along side docopt. I would choose either one of the two.

**Comment by SeeSpotRun** [comment]
I'm not sure you're going to have that either/or option because I doubt this PR is going to get merged.  For one thing it's going to break if you have a filename that includes a doublequote at the start of the name:
```
$ touch '"a file"
$ ./move.py '"a file' 'b file'
```
(works fine currently but breaks with this PR)

Anyway what's so hard about:
```
def my_app(commandline_as_single_string):
    args = shlex.split(command_string)
    arguments = docopt(__doc__, args)
```

**Comment by capaximperii** [comment]
@SeeSpotRun yep definitely better. Thank you.

**Comment by SeeSpotRun** [comment]
@capaximperii maybe close this PR?

**Pull request closed without merging**
